name: orgro
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  org_parser:
    git:
      url: ../org_parser
  cupertino_icons: ^0.1.2
  google_fonts: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

