name: orgro
description: An Org file viewer
version: 1.14.0+39
homepage: https://github.com/amake/orgro

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  dynamic_fonts: ^2.0.0
  # dynamic_fonts:
  #   path: ../dynamic-fonts-flutter
  file_picker_writable: ^2.0.0-nullsafety.2
  # file_picker_writable:
  #   path: ../file_picker_writable
    # git:
    #   url: https://github.com/amake/file_picker_writable.git
    #   ref: android-file-not-found
  flutter:
    sdk: flutter
  flutter_charset_detector: ^0.3.0
  # flutter_charset_detector:
  #   path: ../flutter_charset_detector
  google_fonts: ^2.0.0
  http: ^0.13.0
  intl: ^0.17.0
  native_state: ^1.1.0
  org_flutter: ^0.9.0
  # org_flutter:
  #   path: ../org_flutter
  shared_preferences: ^2.0.0
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/orgro-manual.org
    - assets/fonts/
