name: orgro
description: An Org file viewer
version: 1.12.0+33
homepage: https://github.com/amake/orgro

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  org_flutter: ^0.8.0
  # org_flutter:
  #   path: ../org_flutter
  google_fonts: ^1.0.0
  url_launcher: ^5.4.1
  file_picker_writable: ^1.1.1+4
  # file_picker_writable:
  #   path: ../file_picker_writable
    # git:
    #   url: https://github.com/amake/file_picker_writable.git
    #   ref: android-file-not-found
  http: ^0.12.0+4
  shared_preferences: '>=0.5.7+3 <2.0.0'
  intl: ^0.16.1
  native_state: ^1.1.0
  dynamic_fonts: ^1.1.0
  # dynamic_fonts:
  #   path: ../dynamic-fonts-flutter
  flutter_charset_detector: ^0.1.0
  # flutter_charset_detector:
  #   path: ../flutter_charset_detector

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/orgro-manual.org
    - assets/fonts/
