name: orgro
description: An Org Mode file viewer
version: 1.41.0+103
homepage: https://orgro.org

publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ^3.24.3

dependencies:
  cached_network_image: ^3.0.0
  # dart_pg: ^1.1.5
  dart_pg:
    # path: ../dart-pg
    # Using private fork for sync API
    # https://github.com/web-of-trust/dart-pg/issues/4
    git:
      url: https://github.com/amake/dart-pg.git
      ref: sync
  dynamic_fonts: ^2.2.0
  # dynamic_fonts:
  #   path: ../dynamic-fonts-flutter
  # file_picker_writable: ^2.1.0
  file_picker_writable:
    # path: ../file_picker_writable
    # Using private fork pending merge of
    # https://github.com/hpoul/file_picker_writable/pull/20
    git:
      url: https://github.com/amake/file_picker_writable.git
      ref: directory-picker
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  flutter_cache_manager: ^3.3.0
  flutter_charset_detector: ^4.0.0
  # flutter_charset_detector:
  #   path: ../flutter_charset_detector/flutter_charset_detector
  flutter_slidable: ^3.0.1
  google_fonts: ^6.0.0
  http: ^1.1.0
  intl: ^0.19.0
  org_flutter: ^7.2.0
  # org_flutter:
    # path: ../org_flutter
  path_provider: ^2.0.9
  share_plus: ^10.0.1
  shared_preferences: ^2.0.0
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/manual/
    - assets/manual/data/C2/59CE94-D4C8-4C4F-9C9E-9ABE446E7DA3/
    - assets/fonts/
    - assets/test/
    - assets/licenses/

dependency_overrides:
  # Work around https://github.com/letsar/flutter_slidable/issues/488
  flutter_slidable:
    git:
      url: https://github.com/letsar/flutter_slidable.git
      ref: master
