name: orgro
description: An Org file viewer
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  org_parser:
    # path: ../org_parser
    git:
      url: https://github.com/amake/org_parser.git
  cupertino_icons: ^0.1.2
  google_fonts: ^0.3.7
  url_launcher: ^5.4.1
  file_picker: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
