name: orgro
description: An Org Mode file viewer
version: 1.19.0+47
homepage: https://orgro.org

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.3.0-24.1.pre"

dependencies:
  cached_network_image: ^3.0.0
  dynamic_fonts: ^2.0.0
  # dynamic_fonts:
  #   path: ../dynamic-fonts-flutter
  # file_picker_writable: ^2.0.0
  file_picker_writable:
  #   path: ../file_picker_writable
    git:
      url: https://github.com/amake/file_picker_writable.git
      ref: directory-picker
  flutter:
    sdk: flutter
  flutter_charset_detector: ^1.0.0
  # flutter_charset_detector:
  #   path: ../flutter_charset_detector
  google_fonts: ^2.0.0
  http: ^0.13.0
  intl: ^0.17.0
  org_flutter: ^1.4.0
  # org_flutter:
    # path: ../org_flutter
  shared_preferences: ^2.0.0
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/manual/
    - assets/fonts/
