name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: 'beta'
        flutter-version: '3.14.0-0.2.pre'
    - name: Install dependencies
      run: flutter pub get
    - name: Analyze
      run: flutter analyze
    - name: Run tests
      run: flutter test test
