name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        # Revert to stable due to Android issue in Flutter 3.25+
        # https://github.com/amake/orgro/commit/2319ea7f598e89f29155497ca5e88b2532852a46
        channel: stable
        flutter-version: 3.24.x
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: make test flutter=flutter
